### ISSUE TITLE
Clear-button invert-checkbox

### ISSUE THREAD

**Issue by evenover** [bitfocus/companion-module-generic-swp08#10]
After a bit of programming buttons i found that I want the Clear levels function to be clear levels and not select all. Because now it takes much more time to deselect all levels i do not want to route to than to select all.

I think it actually it should be standard deselect all levels and then maybe a toggle-box to invert it to select all.

**Comment by daniep01** [comment]
Done, hope this is what you meant!

<img width="647" alt="image" src="https://user-images.githubusercontent.com/17852298/124486420-7cea3c00-dda5-11eb-80a7-c543466b4c82.png">

**Comment by evenover** [comment]
Yep, thats it! Awesome

**Comment by evenover** [comment]
This is working as intended 👍
