### ISSUE TITLE
SWP-08 VSM Interface

### ISSUE THREAD

**Issue by krezlic** [bitfocus/companion-module-generic-swp08#13]
Hi,

I am able to see cross points on VSM via SWP-08 however cannot make my own cross points 

Get a list of errors when attempting cross point.
Have setup key as set cross point with a TAKE but also just as a cross point.

21.07.26 16:58:27 instance(SW-P-08): Unknown response code 8
21.07.26 16:58:18 instance(SW-P-08): Unable to verify list of implemented commands
21.07.26 16:58:18 instance(SW-P-08): Crosspoint 1>21 level 1
21.07.26 16:58:18 instance(SW-P-08): Unable to verify list of implemented commands
21.07.26 16:58:17 device(emulator): Button 1.20 pressed

**Comment by krezlic** [comment]
Here is some more of the console

21.07.26 17:06:08 instance(SW-P-08): Unknown response code 8
21.07.26 17:05:59 instance(SW-P-08): Source 108 routed to destination 69 on level 1
21.07.26 17:05:59 instance(SW-P-08): Source 100 routed to destination 71 on level 1
21.07.26 17:05:59 instance(SW-P-08): Source 10 routed to destination 8 on level 1
21.07.26 17:05:57 instance(SW-P-08): Source 92 routed to destination 10 on level 1
21.07.26 17:05:56 instance(SW-P-08): Source 91 routed to destination 10 on level 1
21.07.26 17:05:54 instance(SW-P-08): Source 123 routed to destination 11 on level 1
21.07.26 17:05:53 instance(SW-P-08): Source 3 routed to destination 9 on level 1
21.07.26 17:05:51 instance(SW-P-08): Source 100 routed to destination 68 on level 1
21.07.26 17:05:51 instance(SW-P-08): Source 4 routed to destination 7 on level 1
21.07.26 17:05:49 instance(SW-P-08): Source 90 routed to destination 10 on level 1
21.07.26 17:05:48 instance(SW-P-08): Unknown response code 8
21.07.26 17:05:48 instance(SW-P-08): Source 3 routed to destination 11 on level 1
21.07.26 17:05:36 instance(SW-P-08): Unknown response code 8
21.07.26 17:05:27 instance(SW-P-08): Source 123 routed to destination 11 on level 1
21.07.26 17:05:25 instance(SW-P-08): Unknown response code 8
21.07.26 17:05:16 instance(SW-P-08): Source 6 routed to destination 11 on level 1
21.07.26 17:05:12 instance(SW-P-08): Unknown response code 8
21.07.26 17:05:03 instance(SW-P-08): Source 123 routed to destination 11 on level 1
21.07.26 17:05:01 instance(SW-P-08): Unknown response code 8
21.07.26 17:04:51 instance(SW-P-08): Source 6 routed to destination 11 on level 1
21.07.26 17:04:45 instance(SW-P-08): Source 123 routed to destination 11 on level 1
21.07.26 17:04:41 instance(SW-P-08): Source 11 routed to destination 10 on level 1
21.07.26 17:04:38 instance(SW-P-08): Source 1 routed to destination 10 on level 1
21.07.26 17:04:36 instance(SW-P-08): Source 2 routed to destination 10 on level 1
21.07.26 17:04:35 instance(SW-P-08): Source 3 routed to destination 10 on level 1
21.07.26 17:04:32 instance(SW-P-08): Source 4 routed to destination 10 on level 1
21.07.26 17:04:27 instance(SW-P-08): Source 6 routed to destination 10 on level 1
21.07.26 17:04:26 instance(SW-P-08): Source 5 routed to destination 10 on level 1
21.07.26 17:04:26 instance(SW-P-08): Source 6 routed to destination 11 on level 1
21.07.26 17:04:25 instance(SW-P-08): Source 9 routed to destination 10 on level 1
21.07.26 17:04:25 device(emulator): Button 1.2 released
21.07.26 17:04:25 instance(SW-P-08): Unable to verify list of implemented commands
21.07.26 17:04:25 instance(SW-P-08): Crosspoint 1>21 level 1
21.07.26 17:04:25 instance(SW-P-08): Unable to verify list of implemented commands
21.07.26 17:04:25 device(emulator): Button 1.2 pressed

**Comment by daniep01** [comment]
I think this is the first time the module has been used with VSM, previously we have tested with Ultrix. Can you post more information about VSM - capabilities, etc? 

Response code 8 is not in the SWP08 spec that I am using.

The log entry about verifying the list of supported commands occurs because Companion expects the router to respond to a request asking for a list of commands that can be used when the connection is first established.

**Comment by krezlic** [comment]
Hey Daniel, 

Yeh as far as I know its just Probell SWP-08 - how can I grab more info for you?
I think Riedel MicroN also talks this same SWP-08 as we can control it also with VSM.

**Comment by daniep01** [comment]
I would really like to know what is in response 8 and what it means but only Lavo will be able to tell us that. For the initial check on supported commands I can make this optional and then you can disable it. Would you be able to help with testing?

**Comment by krezlic** [comment]
Hi,

More than happy with testing

N

**Comment by daniep01** [comment]
Here is a link to a test build. It adds an option in the module config to disable the supported commands check and also prints more data to the log when an unknown response is recevied. You may need to delete and re-add the module to see the changes.

https://we.tl/t-KbpoDTEAWa

**Comment by krezlic** [comment]
Thanks mate I’ll check it in the morning as need to rewatch the ethernet - can’t do that remotely unfortunately.

**Comment by krezlic** [comment]
Morning! 

Here is what happens when the instance boots.
The cross points are routes that are happening on the system currently.

On BOOT:

21.07.27 11:12:45 instance(SW-P-08): Source 2 routed to destination 3 on level 1
21.07.27 11:12:45 instance(SW-P-08): Source 90 routed to destination 9 on level 1
21.07.27 11:12:41 instance(SW-P-08): Source 25 routed to destination 10 on level 1
21.07.27 11:12:40 instance(SW-P-08): Source 91 routed to destination 2 on level 1
21.07.27 11:12:40 instance(SW-P-08): Source 24 routed to destination 10 on level 1
21.07.27 11:12:39 instance(SW-P-08): Source 23 routed to destination 10 on level 1
21.07.27 11:12:39 instance(SW-P-08): Source 24 routed to destination 10 on level 1
21.07.27 11:12:39 instance(SW-P-08): Source 22 routed to destination 1 on level 1
21.07.27 11:12:38 instance(SW-P-08): Source 25 routed to destination 10 on level 1
21.07.27 11:12:37 instance(SW-P-08): 8, 1, 24 7, 8, 1, 24
21.07.27 11:12:37 instance(SW-P-08): Unknown response code 8

On Cross Point ( key action set as SET crosspoint src 1 dst 21 level 1 )

21.07.27 11:15:14 instance(SW-P-08): Source 17 routed to destination 10 on level 1
21.07.27 11:15:12 instance(SW-P-08): Source 16 routed to destination 10 on level 1
21.07.27 11:15:06 instance(SW-P-08): Source 15 routed to destination 10 on level 1
21.07.27 11:15:05 instance(SW-P-08): Source 16 routed to destination 10 on level 1
21.07.27 11:15:03 instance(SW-P-08): Source 15 routed to destination 10 on level 1
21.07.27 11:14:58 instance(SW-P-08): 8, 1, 24
21.07.27 11:14:58 instance(SW-P-08): Unknown response code 8
21.07.27 11:14:51 device(emulator): Button 1.2 released
21.07.27 11:14:51 device(emulator): Button 1.2 pressed
21.07.27 11:14:51 instance(SW-P-08): Unable to verify list of implemented commands
21.07.27 11:14:51 instance(SW-P-08): Crosspoint 1>21 level 1
21.07.27 11:14:49 instance(SW-P-08): Source 56 routed to destination 11 on level 1
21.07.27 11:14:48 instance(SW-P-08): Source 55 routed to destination 11 on level 1

**Comment by krezlic** [comment]
Furthermore a stacked key with the following setup with 20ms delays

Select Level :1
Select Source:1
Select Destination:21
Take

21.07.27 11:17:57 instance(SW-P-08): Source 41 routed to destination 9 on level 1
21.07.27 11:17:51 instance(SW-P-08): Source 18 routed to destination 11 on level 1
21.07.27 11:17:50 instance(SW-P-08): Source 28 routed to destination 11 on level 1
21.07.27 11:17:50 device(emulator): Button 1.2 released
21.07.27 11:17:50 instance(SW-P-08): Unable to verify list of implemented commands
21.07.27 11:17:50 instance(SW-P-08): Crosspoint 1>21 level 3
21.07.27 11:17:50 instance(SW-P-08): Unable to verify list of implemented commands
21.07.27 11:17:50 instance(SW-P-08): Crosspoint 1>21 level 2
21.07.27 11:17:50 instance(SW-P-08): Unable to verify list of implemented commands
21.07.27 11:17:50 instance(SW-P-08): Crosspoint 1>21 level 1
21.07.27 11:17:50 instance(SW-P-08): Unable to verify list of implemented commands
21.07.27 11:17:50 instance(SW-P-08): Unable to verify list of implemented commands
21.07.27 11:17:50 instance(SW-P-08): Unable to verify list of implemented commands
21.07.27 11:17:50 device(emulator): Button 1.2 pressed

**Comment by krezlic** [comment]
Deleted the connection and reinstalled the build again.
Setup profile with 1 level and disabled request supported commands and request names 

21.07.27 11:46:12 instance(SW-P-08): Source 53 routed to destination 9 on level 1
21.07.27 11:46:08 instance(SW-P-08): Source 55 routed to destination 9 on level 1
21.07.27 11:46:07 instance(SW-P-08): Source 54 routed to destination 9 on level 1
21.07.27 11:46:04 instance(SW-P-08): Source 55 routed to destination 9 on level 1
21.07.27 11:46:02 instance(SW-P-08): Source 61 routed to destination 9 on level 1
21.07.27 11:46:00 instance(SW-P-08): Source 5 routed to destination 11 on level 1
21.07.27 11:45:59 instance(SW-P-08): Source 56 routed to destination 10 on level 1
21.07.27 11:45:56 instance(SW-P-08): Source 55 routed to destination 10 on level 1
21.07.27 11:45:55 instance(SW-P-08): Source 54 routed to destination 10 on level 1
21.07.27 11:45:54 instance(SW-P-08): Source 5 routed to destination 9 on level 1
21.07.27 11:45:54 instance(SW-P-08): Source 53 routed to destination 10 on level 1
21.07.27 11:45:53 instance(SW-P-08): Source 51 routed to destination 10 on level 1
21.07.27 11:45:51 instance(SW-P-08): Source 52 routed to destination 11 on level 1
21.07.27 11:45:51 instance(SW-P-08): Source 52 routed to destination 10 on level 1
21.07.27 11:45:50 instance(SW-P-08): Source 51 routed to destination 10 on level 1
21.07.27 11:45:50 instance(SW-P-08): Source 52 routed to destination 10 on level 1
21.07.27 11:45:50 instance(SW-P-08): Source 51 routed to destination 10 on level 1
21.07.27 11:45:49 instance(SW-P-08): Source 52 routed to destination 10 on level 1
21.07.27 11:45:49 instance(SW-P-08): Source 51 routed to destination 10 on level 1
21.07.27 11:45:49 instance(SW-P-08): Source 52 routed to destination 10 on level 1
21.07.27 11:45:48 instance(SW-P-08): Source 1 routed to destination 9 on level 1
21.07.27 11:45:48 instance(SW-P-08): Source 51 routed to destination 10 on level 1
21.07.27 11:45:47 instance(SW-P-08): Source 52 routed to destination 10 on level 1
21.07.27 11:45:45 instance(SW-P-08): Source 90 routed to destination 9 on level 1
21.07.27 11:45:43 instance(SW-P-08): Source 91 routed to destination 9 on level 1
21.07.27 11:45:39 instance(SW-P-08): Source 113 routed to destination 81 on level 1
21.07.27 11:45:38 instance(SW-P-08): Source 100 routed to destination 78 on level 1
21.07.27 11:45:38 instance(SW-P-08): Source 112 routed to destination 77 on level 1
21.07.27 11:45:37 instance(SW-P-08): Source 90 routed to destination 9 on level 1
21.07.27 11:45:36 instance(SW-P-08): Source 116 routed to destination 96 on level 1
21.07.27 11:45:35 instance(SW-P-08): Source 100 routed to destination 98 on level 1
21.07.27 11:45:35 instance(SW-P-08): Source 117 routed to destination 100 on level 1
21.07.27 11:45:33 instance(SW-P-08): Source 100 routed to destination 110 on level 1
21.07.27 11:45:33 instance(SW-P-08): Source 120 routed to destination 112 on level 1
21.07.27 11:45:30 instance(SW-P-08): 8, 1, 24
21.07.27 11:45:30 instance(SW-P-08): Unknown response code 8
21.07.27 11:45:21 instance(SW-P-08): Source 52 routed to destination 9 on level 1
21.07.27 11:45:20 instance(SW-P-08): Source 51 routed to destination 9 on level 1
21.07.27 11:45:14 instance(SW-P-08): Source 5 routed to destination 9 on level 1
21.07.27 11:45:11 instance(SW-P-08): 8, 1, 24
21.07.27 11:45:11 instance(SW-P-08): Unknown response code 8
21.07.27 11:45:02 instance(SW-P-08): Source 6 routed to destination 9 on level 1
21.07.27 11:45:00 instance(SW-P-08): Source 7 routed to destination 9 on level 1
21.07.27 11:44:59 instance(SW-P-08): Source 5 routed to destination 9 on level 1
21.07.27 11:44:56 instance(SW-P-08): Source 7 routed to destination 9 on level 1
21.07.27 11:44:53 instance(SW-P-08): Source 53 routed to destination 10 on level 1
21.07.27 11:44:51 instance(SW-P-08): 8, 1, 24
21.07.27 11:44:51 instance(SW-P-08): Unknown response code 8
21.07.27 11:44:42 instance(SW-P-08): Source 52 routed to destination 10 on level 1
21.07.27 11:44:40 instance(SW-P-08): Source 5 routed to destination 9 on level 1
21.07.27 11:44:33 instance(SW-P-08): 8, 1, 24
21.07.27 11:44:33 instance(SW-P-08): Unknown response code 8
21.07.27 11:44:33 instance(SW-P-08): 8, 1, 24 7, 8, 1, 24
21.07.27 11:44:33 instance(SW-P-08): Unknown response code 8
21.07.27 11:44:22 instance(SW-P-08): 8, 1, 24
21.07.27 11:44:22 instance(SW-P-08): Unknown response code 8
21.07.27 11:44:13 device(emulator): Button 1.2 released
21.07.27 11:44:13 instance(SW-P-08): Source 2 routed to destination 21 on level 1
21.07.27 11:44:13 device(emulator): Button 1.2 pressed
21.07.27 11:44:13 instance(SW-P-08): Crosspoint 2>21 level 1
21.07.27 11:44:08 instance(SW-P-08): Source 2 routed to destination 9 on level 1
21.07.27 11:44:07 instance(SW-P-08): Source 1 routed to destination 9 on level 1
21.07.27 11:44:05 instance(SW-P-08): Source 90 routed to destination 9 on level 1
21.07.27 11:44:01 instance(SW-P-08): Source 2 routed to destination 9 on level 1
21.07.27 11:44:00 instance(SW-P-08): Source 1 routed to destination 9 on level 1
21.07.27 11:43:56 instance(SW-P-08): 8, 1, 24
21.07.27 11:43:56 instance(SW-P-08): Unknown response code 8
21.07.27 11:43:47 instance(SW-P-08): Source 90 routed to destination 9 on level 1
21.07.27 11:43:47 instance(SW-P-08): Source 7 routed to destination 11 on level 1
21.07.27 11:43:45 device(emulator): Button 1.2 released
21.07.27 11:43:44 instance(SW-P-08): Source 1 routed to destination 21 on level 1
21.07.27 11:43:44 device(emulator): Button 1.2 pressed
21.07.27 11:43:44 instance(SW-P-08): Crosspoint 1>21 level 1
21.07.27 11:43:43 instance(SW-P-08): Source 30 routed to destination 10 on level 1
21.07.27 11:43:41 instance(SW-P-08): Source 52 routed to destination 9 on level 1
21.07.27 11:43:36 instance(SW-P-08): Source 1 routed to destination 10 on level 1
21.07.27 11:43:30 instance(SW-P-08): Source 51 routed to destination 9 on level 1
21.07.27 11:43:29 instance(SW-P-08): Source 114 routed to destination 85 on level 1
21.07.27 11:43:28 instance(SW-P-08): Source 100 routed to destination 102 on level 1
21.07.27 11:43:28 instance(SW-P-08): Source 118 routed to destination 101 on level 1
21.07.27 11:43:27 instance(SW-P-08): Source 116 routed to destination 95 on level 1
21.07.27 11:43:26 instance(SW-P-08): Source 52 routed to destination 9 on level 1
21.07.27 11:43:25 instance(SW-P-08): Source 111 routed to destination 73 on level 1
21.07.27 11:43:25 instance(SW-P-08): Source 51 routed to destination 9 on level 1
21.07.27 11:43:25 instance(SW-P-08): Source 100 routed to destination 90 on level 1
21.07.27 11:43:25 instance(SW-P-08): Source 115 routed to destination 89 on level 1
21.07.27 11:43:23 instance(SW-P-08): Source 113 routed to destination 82 on level 1
21.07.27 11:43:23 instance(SW-P-08): Source 100 routed to destination 79 on level 1
21.07.27 11:43:23 instance(SW-P-08): Source 112 routed to destination 78 on level 1
21.07.27 11:43:20 device(emulator): Button 1.2 released
21.07.27 11:43:20 instance(SW-P-08): Source 1 routed to destination 21 on level 1
21.07.27 11:43:20 device(emulator): Button 1.2 pressed
21.07.27 11:43:20 instance(SW-P-08): Crosspoint 1>21 level 1
21.07.27 11:43:19 instance(SW-P-08): Source 5 routed to destination 9 on level 1
21.07.27 11:43:18 instance(SW-P-08): Source 93 routed to destination 10 on level 1
21.07.27 11:43:18 instance(SW-P-08): Source 92 routed to destination 10 on level 1
21.07.27 11:43:17 instance(SW-P-08): Source 91 routed to destination 10 on level 1
21.07.27 11:43:13 instance(SW-P-08): Source 90 routed to destination 10 on level 1
21.07.27 11:43:12 instance(SW-P-08): Source 2 routed to destination 10 on level 1
21.07.27 11:43:11 instance(SW-P-08): Source 1 routed to destination 10 on level 1
21.07.27 11:43:09 instance(SW-P-08): Source 2 routed to destination 10 on level 1
21.07.27 11:43:06 instance(SW-P-08): Source 1 routed to destination 10 on level 1
21.07.27 11:43:03 instance(SW-P-08): Source 90 routed to destination 10 on level 1
21.07.27 11:42:59 instance(SW-P-08): Source 93 routed to destination 10 on level 1
21.07.27 11:42:59 instance(SW-P-08): Source 92 routed to destination 10 on level 1
21.07.27 11:42:59 instance(SW-P-08): Source 91 routed to destination 10 on level 1
21.07.27 11:42:58 instance(SW-P-08): Source 90 routed to destination 10 on level 1
21.07.27 11:42:57 instance(SW-P-08): Source 91 routed to destination 10 on level 1
21.07.27 11:42:56 instance(SW-P-08): Source 90 routed to destination 10 on level 1
21.07.27 11:42:56 instance(SW-P-08): Source 54 routed to destination 11 on level 1
21.07.27 11:42:55 instance(SW-P-08): Source 56 routed to destination 11 on level 1
21.07.27 11:42:53 instance(SW-P-08): Source 53 routed to destination 11 on level 1
21.07.27 11:42:50 instance(SW-P-08): Source 90 routed to destination 2 on level 1
21.07.27 11:42:49 instance(SW-P-08): Source 102 routed to destination 46 on level 1
21.07.27 11:42:49 instance(SW-P-08): Source 51 routed to destination 2 on level 1
21.07.27 11:42:48 instance(SW-P-08): Source 103 routed to destination 50 on level 1
21.07.27 11:42:48 instance(SW-P-08): Source 51 routed to destination 3 on level 1
21.07.27 11:42:45 instance(SW-P-08): 8, 1, 24
21.07.27 11:42:45 instance(SW-P-08): Unknown response code 8
21.07.27 11:42:45 instance(nvhGyDagE): instance configuration updated
21.07.27 11:42:24 instance(nvhGyDagE): instance add generic-swp08 SW-P-08
21.07.27 11:42:05 instance(2UKNLP90D): instance deleted

**Comment by krezlic** [comment]
The good news is that i can now switch cross points just tested based off the message above

**Comment by daniep01** [comment]
Response message 8 seems to only include a few bytes, maybe we can just ignore this. Unless we receive any new information I don't think there is anything else I can do. Are you happy enough that you can do what you need now?

**Comment by krezlic** [comment]
Yeah, that's fine.

It’s working a treat that 8, messages comes in every so often…. I’ll ask
some developer mates if they know what it is

**Comment by daniep01** [comment]
If you have any contacts at Lavo and they can tell us what it does then I'm happy to add the code in the future.
