### ISSUE TITLE
Source of destination name wrong

### ISSUE THREAD

**Issue by evenover** [bitfocus/companion-module-generic-swp08#14]
When I select a destination and look at the source of destination, it obtains the correct number, but the name is offset by 16. 

So it shows for example that source 201 is routed but shows the name of 217

**Comment by daniep01** [comment]
I'll try and find out what is causing this

**Comment by daniep01** [comment]
Have you verified that the list of source names in the list of variables is correct? It could be that this list has gaps or is offset.

**Comment by evenover** [comment]
The list of variables looks right. Let me check for anything suspicious tomorrow.

**Comment by evenover** [comment]
It seems like this happends from when a new config is pushed to the ultrix. So this can be a ultrix-fault.

**Comment by daniep01** [comment]
I suggest you do a "get names" command after sending changes in the ultrix dashboard configuration.
