### ISSUE TITLE
Feedback of a certain crosspoint

### ISSUE THREAD

**Issue by CharlesSicard** [bitfocus/companion-module-generic-swp08#17]
Hi all, 

For a particular use, I need to perform an action if a certain crosspoint is active in the matrix. I see feedback possible for a specified source when a destination is selected, so that's not far.

I'll have a look at the source code next week, see if I manage to do it myself, but if a dev that knows its way around this module, and feels like to investigate the matter, that would be awesome ! I'll share if I manage to do it obviously.

Thanks !

**Comment by daniep01** [comment]
This is something that could be done, there's a slight complication in the fact that you need to allow the user to specify the which level(s) need to be compared and then do the feedback check on all these levels.

**Comment by CharlesSicard** [comment]
Hi daniep01,

I have been working on the matter, and indeed the level checking isn't as easy as it sounds.
Never the less, right now I don't really need this, as I am only using one level. I have implemented a new feedback with this code :

`		case 'source_dest_xpt': {
			// look for this dest in route table
			console.log('xpt feedback ' + feedback.options.dest + ':' + feedback.options.source)
			for (var i = 0; i < self.routeTable.length; i++) {
				if (self.routeTable[i].dest === feedback.options.dest) {
					if (self.routeTable[i].source === feedback.options.source) {
						return true
					}
				}
			}
			return false	
			break
		}`

This works fine when I activate the feedback, but it doesn't trigger it when there is a change. Am I missing something ?

**Comment by CharlesSicard** [comment]
Daniep01, 

here is where I am. It's missing the check level part so far.
I added a self.checkFeedbacks() at the end of the crosspoint_connected functions to check for feedbacks everytime a xpt is made.

https://github.com/CharlesSicard/companion-module-generic-swp08

**Comment by daniep01** [comment]
Good work, thanks. Have you managed to test with the hardware and see it working?

**Comment by CharlesSicard** [comment]
Yes, tested with Lawo VSM and it works

**Comment by LtechVideohouse** [comment]
look @ #20 
I have trouble to get the choice of destination in the feedback button.
