### ISSUE TITLE
SW-P-08: Source Routed to Destination but no destination choice

### ISSUE THREAD

**Issue by LtechVideohouse** [bitfocus/companion-module-generic-swp08#20]
I use the SWP08 protocol, it works, but.

Wen you need a feedback, and use "SW-P-08: Source Routed to Destination", you can set the source, but you don't have the destination choice in the feedback button

In the action button:"SW-P-08: Set crosspoint" you have choice of level, source and destination.

Problem when you need to switch two different destination in one page, you can't get feedback of both destination

![Source Routed to Destination but no destination choice](https://github.com/bitfocus/companion-module-generic-swp08/assets/159143179/e6ad6d28-2264-4e87-8404-b95186bb9c6a)

Thank you

**Comment by phillipivan** [comment]
These feedback is for the the selected destination. I have added a seperate feedback that allows selecting the source and destination.
