### ISSUE TITLE
Set crosspoint by name action not working

### ISSUE THREAD

**Issue by benturnbull1991** [bitfocus/companion-module-generic-swp08#26]
I have recently updated to 3.4.0 and the "Set crosspoint by name" action has broken. The names all populate fine but nothing is changed when triggering the action. I am able to use the "Set crosspoint" action and define the actual numbers with no issue, so the integration is working. I'm just not able to set the crosspoint by selecting the names which is really useful for quick programming. 
This particular case is using a Ross Ultrix.

**Comment by phillipivan** [comment]
This has been patched by @haakonnessjoen already in v2.0.2

**Comment by phillipivan** [comment]
You can download a build of the module [here ](https://github.com/bitfocus/companion-module-generic-swp08/releases/tag/v2.0.2)prior to the release of 3.4.1.
