### ISSUE TITLE
variables for label names which can be added to buttons

### ISSUE THREAD

**Issue by daniep01** [bitfocus/companion-module-generic-swp08#3]
This issue for a variable that can be used as the name of the button? ie, a separate variable for every source label and every destination label?

**Comment by evenover** [comment]
Yes, thats what i would like to have.

**Comment by daniep01** [comment]
Variables containing labels are now created for each every source and destination

https://we.tl/t-pfLKnk3ytO

**Comment by evenover** [comment]
I Will test this out monday.

**Comment by evenover** [comment]
I have tested it out now and it seems to be working :) I dont think it needs to have a prefix with the routernumber like: 20: EXT 1 because thats steals alot of buttonspace when i get to 500.

**Comment by daniep01** [comment]
Yes, I did wonder about that. Presumably the prefix is useful on the dropdown menus when selecting source or destination?

**Comment by evenover** [comment]
Yes, that would be fine 👍

**Comment by daniep01** [comment]
Done ✅

**Comment by evenover** [comment]
Now i have tested a bit more. After the inital read i did when i installed the newest test-build it seems to be something wrong with the labels of sources 17-32 and all above 256 comes up as "undefined". It only reads 468 sources even though I got 500, so 32 is missing.
Hopefully this helps you out.

**Comment by daniep01** [comment]
Until I see the spec on how labels are returned this part of the code is based on guesswork so it is possible that there will be issues like this. Have you tried the get names action again? Is it the same result?

**Comment by chibiconsulting** [comment]
If the DLE expansion to DLE DLE on transmission and DLE DLE to DLE compression on reception is not yet implemented, this might be a symptom of that.
DLE = 10 HEX

**Comment by daniep01** [comment]
The change to the labels to remove the prefix is in this build https://we.tl/t-UyvfRNLX8A
I still need to look at the DLE DLE receive processing.

**Comment by evenover** [comment]
Tested, No prefix any more.

**Comment by daniep01** [comment]
The variables are working, I've made a new issue for the labels
