### ISSUE TITLE
variable with the source name of selected destination

### ISSUE THREAD

**Issue by daniep01** [bitfocus/companion-module-generic-swp08#4]
Is this a single global variable called `current_source` or is it a long list of variables, one for every destination?

**Comment by evenover** [comment]
This would be a "Current Source".

**Comment by daniep01** [comment]
What would this variable contain when the destination has multiple sources on different levels?

**Comment by evenover** [comment]
It should be the source of the selected destination and selected level. 

If multiple levels are selected it should be level 1.

**Comment by daniep01** [comment]
I've added this functionality for both source name and source number. There is a variable for every level as defined in the module config as doing it on selected level(s) would be quite messy I think.

https://we.tl/t-gM9Firsk5K

**Comment by evenover** [comment]
This is working. To get the functionality i want i can just at "change button text" on the destination select button to select the right variable on the "Source of"-button.
