### ISSUE TITLE
I used the "select destination" and when I choose one destination and then another, the previously chosen destination inherit the now selected destinations destination(complicated)

### ISSUE THREAD

**Issue by daniep01** [bitfocus/companion-module-generic-swp08#6]
> I think that Evertz implements this as a virtual destination which is a destination that can then be used as a source somewhere else. I do not recall SW-P-08 ever having that capability. Might make sense as a separate, more generic request to provide that function for all router protocols. If a range of virtual sources/destinations are defined as being linked and held separate from the router, requests to / from those can be translated on the fly and dropped back to the native router protocol. Not a trivial problem by any means.

This is a quite advanced feature and in my opinion companion is generally aimed at casual or supplementary use cases. For this kind of complexity you should probably be using the Ross panels or similar.

**Comment by evenover** [comment]
This was actually a issue and not a request.
When I pressed a button with a destination and then pressed a new destination the previuos button would inherit the next buttons destination. When i used the select destination by name it did not happen. 

This request/issue can be closed, if it doesnt happen any more.

**Comment by daniep01** [comment]
Thanks for the clarification.
