### ISSUE TITLE
Feedback color change when Destination AND level selected

### ISSUE THREAD

**Issue by evenover** [bitfocus/companion-module-generic-swp08#9]
I want a feedback where the background color changes when a destination and level is selected.

Usecase:
I have many pages wtih destinations for embedding audio in the ultrix. 8 buttons have the same destination, but different levels. When i select one of the 8, all of them light up because feedback only see the destination selected.

Example:
A button with destination 10 and level 2 is selected then destinaion 10 and level 3.

**Comment by daniep01** [comment]
Added in https://we.tl/t-UyvfRNLX8A

**Comment by evenover** [comment]
Tested, seems to be worikg as intended 👍
